# Name of the executable
TARGET = task3_1

# Source file
SRC = task3_2.c

# Compiler
CC = gcc

# Compiler flags (optional: -Wall for warnings, -g for debugging)
CFLAGS = -Wall -g

# Build target
$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

# Clean target to delete compiled files
clean:
	rm -f $(TARGET)
